# A service to set a new polygon with holes.
# Request fields:
planning_msgs/PolygonWithHolesStamped polygon # The new polygon.
---
# Response fields:
bool success # True on success, false on polygon error.
