Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = []

src += Glob('source/Console/*.c')
src += Glob('source/Copter/*.c')
src += Glob('source/FileManager/*.c')
src += Glob('source/Global/*.c')
# src += Split("""
# source/INS/AHRS.c
# source/INS/att_estimator.c
# source/INS/pos_estimator.c
# """)
src += Glob('source/LED/*.c')
src += Glob('source/Logger/*.c')
src += Glob('source/Math/*.c')
src += Glob('source/Mavproxy/*.c')
src += Glob('source/Param/*.c')
src += Glob('source/PID/*.c')
src += Glob('source/Sensor/*.c')
#src += Split("""
#source/Sensor/sensor_manager.c
#source/Sensor/calibration.c
#""")
src += Glob('source/STARRYIO/*.c')
src += Glob('source/Statistic/*.c')
src += Glob('source/System/*.c')
src += Glob('source/Test/*.c')
src += Glob('source/Time/*.c')
src += Glob('source/Tools/*.c')
src += Glob('source/uMCN/*.c')
src += Glob('source/YXML/*.c')
src += Glob('source/Tool/*.c')
src += Glob('source/FTP/*.c')
src += Glob('source/INS/simulink/INS_ert_rtw/*.c')
src += Glob('source/INS/simulink/slprj/ert/_sharedutils/*.c')
src += Glob('source/INS/simulink/slprj/ert/CF_INS/*.c')
src += Glob('source/INS/simulink/slprj/ert/SensorProcessing/*.c')


CPPPATH = [cwd + '/include', cwd + '/source/INS/simulink/INS_ert_rtw', cwd + '/source/INS/simulink/INS_ert_rtw/referenced_model_includes',
 cwd + '/source/INS/simulink/slprj/ert/_sharedutils', cwd + '/source/INS/simulink/slprj/ert/CF_INS',
 cwd + '/source/INS/simulink/slprj/ert/SensorProcessing']

group = DefineGroup('Framework', src, depend = [''], CPPPATH = CPPPATH)

Return('group')

